# Generated by Django 4.2.11 on 2024-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheUserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theusername', models.CharField(max_length=50)),
                ('thepassword', models.CharField(max_length=50)),
            ],
        ),
    ]
