# Generated by Django 4.2.11 on 2024-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_theuserentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
