# Generated by Django 4.2.11 on 2024-05-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0006_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('phone_number', models.CharField(max_length=20, verbose_name='电话号码')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
